server:
  port : 9001

spring:
  datasource:
    password: qwe193!1sxz
    url: jdbc:mysql://localhost:3306/vm_authen
    username: vm_admin
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: false
  server:
    servlet:
      session:
        timeout:2h
