server:
  port : 9001

spring:
  datasource:
    password: Aa123456
    url: jdbc:mysql://localhost:3306/vm_authen
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: false
  server:
    servlet:
      session:
        timeout:2h

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs