server:
  port : 9001

spring:
  datasource:
    password: Aa123456
    url: jdbc:mysql://localhost:3306/vm_authen
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:migration
    baseline-on-migrate: false